name: addictionsupportroom
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.4
  cached_network_image: ^3.2.2
  flutter_svg: ^1.1.6
  flutter_screenutil: ^5.6.0
  table_calendar: ^3.0.8
  cloudinary_dart: ^0.0.8
  go_router: ^5.2.0
  dio: ^4.0.6
  smooth_page_indicator: ^1.0.0+2
  flutter_spinkit: ^5.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^6.0.0
  get_it: ^7.2.0
  top_snackbar_flutter: ^3.0.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  build_runner: ^2.1.4

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/svgs/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
